version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf.d:/nginx/conf.d/
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - cart_default
  cart:
    image: chkt/cart
    build: .
    deploy:
        replicas: 5
    depends_on:
      - cassandra-container2
    ports:
      - 8080:8080
      - 8081:8080
      - 8082:8080
      - 8083:8080
      - 8084:8080
    networks:
      - cart_default
  cassandra-container2:
    container_name: cassandra-container2
    image: cassandra:latest
    volumes:
      - '/Users/z00341l/DB/CASSANDRA:/var/lib/cassandra'
    ports:
      - 32816:9042
      - 32817:9160
      - 32818:7000
      - 32819:7001
      - 32820:7199
    networks:
      - cart_default
networks:
    cart_default:
        driver: bridge
